version: "3.8"

services:
  nginx:
    #build:
    #  context: ./nginx
    image: nginx:1.7.9
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - type: volume
        source: shared
        target: /app
      #- ./logs/nginx-access.log:/var/log/nginx/access.log
      #- ./logs/nginx-error.log:/var/log/nginx/error.log
  php-fpm:
    image: local/php:latest
    network_mode: service:nginx
    volumes:
      - storage:/app/storage
      - type: volume
        source: shared
        target: /app
        volume:
          nocopy: false  
volumes:
  shared:
  storage:
networks:
 service-networks:
   name: developer_service-net
   driver: bridge  