apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "getReleaseName" . }}-storage
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
