apiVersion: v1
kind: Secret
metadata:
  name: {{ include "getReleaseName" . }}
  labels: {{- include "getLabels" . | nindent 4 }}
type: Opaque
data:
{{- with .Values.env}}
  {{- range $key, $val := . }}
  {{ $key }}: {{ $val | toString | b64enc | quote }}
  {{- end }}
{{- end }}
  REDIS_HOST_MASTER: {{ include "getRedisHostMaster" . | toString | b64enc | quote }}
  REDIS_HOST_SLAVE: {{ include "getRedisReadServiceName" . | toString | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.envRedis.REDIS_PASSWORD | toString | b64enc | quote }}
  REDIS_PORT: {{ .Values.envRedis.REDIS_PORT | toString | b64enc | quote }}
