{{- $releaseName := include "getReleaseName" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $releaseName  }}-redis-secret
type: Opaque
data:
    REDIS_HOSTNAME_MASTER: {{  include "getRedisHostMasterName" .  | toString | b64enc | quote }}
    REDIS_HOST_MASTER: {{ include "getRedisHostMaster" . | toString | b64enc | quote }}
    REDIS_PASSWORD: {{ .Values.envRedis.REDIS_PASSWORD | toString | b64enc | quote }}
    REDIS_PORT: {{ .Values.envRedis.REDIS_PORT | toString | b64enc | quote }}
