{{- $releaseName := include "getReleaseName" . -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "getRedisAppName" . }}
spec:
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "getRedisPodName" . }}
  serviceName: {{ $releaseName }}-redis-headless-svc
  template:
    metadata:
      labels:
        app: {{ include "getRedisPodName" . }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.redis.terminationGracePeriodSeconds }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "getServiceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.containerRedis.name }}
          {{- with .Values.containerRedis.securityContext }}
          securityContext:
              {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ .Values.containerRedis.image }}
          imagePullPolicy: {{ .Values.containerRedis.imagePullPolicy }}
          ports:
            {{- toYaml .Values.containerRedis.ports | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ $releaseName  }}-redis-secret
          {{- with .Values.containerRedis.livenessProbe}}
          livenessProbe:
              {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.containerRedis.readinessProbe}}
          readinessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
          {{- toYaml .Values.containerRedis.resources | nindent 12  }}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: launch
              mountPath: /script/launch.sh
              subPath: launch.sh
          command:
            - sh
            - -c
            - /script/launch.sh
      volumes:
        - name: launch
          configMap:
            name: {{ $releaseName  }}-redis-config
            defaultMode: 0777
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
